name: 🚀🚀 Basic 👨‍💻Dev - Sec🪲 Ops📉  Workflow 🚀🚀  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  dast:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
    - name: ✅ Checkout
      uses: actions/checkout@v2

    - name: ✅ DAST
      run: | 
        env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
        docker pull registry.fortidevsec.forticloud.com/fdevsec_dast:latest
        docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_dast:latest
