name: Pre Work
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  
  first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1.1
        run: |
          echo "Done 1.1" 
      - name: Step 1.2
        run: |
          echo "Done 1.2"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2.1
        run: |
          echo "Done 1.1" 
      - name: Step 2.2
        run: |
          echo "Done 1.2"
