name: FortiDevSec Scanner SAST CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
            
      # Runs a single command using the runners shell
      - name: GET Status Code
        run: echo "STATUS_CODE=$(curl -s -v -L -I -o /dev/null  -w "%{http_code}" http://web-dvwa.eastus.azurecontainer.io)" >> "$GITHUB_ENV"

      # Runs a set of commands using the runners shell
      - name: Deploy the App
        if:  ${{ !(env.STATUS_CODE==200) }}
        uses: Azure/cli@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: | 
            az group create -n web-dvwa-rg -l eastus
            az container create --name web-dvwa --dns-name-label web-dvwa --image vulnerables/web-dvwa -g web-dvwa-rg

  sast_and_dast_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: SAST
      run: |
        env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
        docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
        docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
            
    - name: DAST
      run: | 
        env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
        docker pull registry.fortidevsec.forticloud.com/fdevsec_dast:latest
        docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_dast:latest